# Bot
bot.username=paynet_monitoring_reporter_bot
bot.token=8212728008:AAF9pX30htvbNdSNSCVtktjGp7nR95XmG9s

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
## Jpa Config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# timezone
app.timezone=Asia/Tashkent
google.spreadsheet-id= 1rqFLPZjwJ9wuTDzCEj9wAaiS_f3mcRMowcCaO1Pi9C4
google.timezone= Asia/Tashkent